### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by umaim** [clancy-chao/Steam-Bundle-Sites-Extension#2]
## Bug fix
- [x] Indiegala My Libraries page exported file name error
- [x] Indiegala My Libraries page buttons position glitches

## Core feature improvement
- [x] Support [Fanatical](https://www.fanatical.com) after Nov. 1st, 2017
- [x] Export Humble keys from [Humble Keys Page](https://www.humblebundle.com/home/keys)
- [x] Hightlight Humble Keys' region restricted infomations

## Other
- [ ] ~~Lightweight (jQuery-free, etc.)~~
